language: node_js
env:
  global:
    - GH_REF: github.com/meishaFE/steam-game-ui.git
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '9'
install:
  - npm install
script:
  - npm run test
  - npm run build
after_script:
  - cd ./dist
  - git init
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${TOKEN_AARON}@${GH_REF}" master:gh-pages